# Generated by Django 3.2.9 on 2021-12-10 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0020_auto_20211210_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 12, 31, 33, 526667, tzinfo=utc)),
        ),
    ]
