# Generated by Django 3.2.9 on 2021-12-10 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0021_auto_20211210_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 19, 1, 25, 412046, tzinfo=utc)),
        ),
    ]
