# Generated by Django 3.2.9 on 2021-11-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productName',
        ),
    ]
