# Generated by Django 3.2.9 on 2021-12-07 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0015_auto_20211207_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 511174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 511174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 511174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 526840, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 18, 31, 47, 526840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 526840, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 526840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 526840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 18, 31, 47, 526840, tzinfo=utc)),
        ),
    ]
