# Generated by Django 3.2.9 on 2021-12-09 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0016_auto_20211208_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 62916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 58928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 58928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 65908, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 5, 17, 32, 65908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 65908, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 66906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 64911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 17, 32, 67904, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='product_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_image/product_gallery/')),
                ('prouct', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='onlineshop.product')),
            ],
        ),
    ]
