# Generated by Django 3.2.9 on 2021-12-09 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0017_auto_20211209_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_gallery',
            old_name='prouct',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 736686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 736686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 5, 40, 12, 752309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 5, 40, 12, 752309, tzinfo=utc)),
        ),
    ]
